name: Run SonarQube on Maven

on: push

jobs:
  build:
      runs-on: ubuntu-latest
      step:
      - users: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven
      - name: Build with maven cloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=sonudeepa_vulnerable-java-maven -Dsonar.organization=gitactionsonarorg -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          
